<a href="https://colab.research.google.com/github/ingridcos/Exercicios-WoMakersCode/blob/main/Desafio_SQL_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('/content/Desafio_SQL_2.db')

df = pd.read_sql('SELECT * FROM customers', conn)
df.head()

   customer_id              nome               email dt_cadastro
0            1      João Pereira      joao@gmail.com  2024-01-10
1            2         Ana Souza       ana@yahoo.com  2024-02-15
2            3       Carlos Lima  carlos@hotmail.com  2024-03-05
3            4  Beatriz Oliveira     bia@outlook.com  2024-04-20
4            5      Pedro Santos     pedro@gmail.com  2024-05-01

In [3]:
tabelas = pd.read_sql(
    "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name;",
    conn
)
tabelas

                                   name
0               categoria_valor_pedidos
1                 cliente_pedido_concat
2                 clientes_ano_cadastro
3         clientes_com_pedidos_distinct
4           clientes_com_pedidos_exists
5   clientes_compraram_todos_tecnologia
6               clientes_nome_maiusculo
7            clientes_total_gasto_pagos
8                             customers
9                     dias_desde_pedido
10              dominios_email_clientes
11                media_movel_3_pedidos
12                          order_items
13                               orders
14                pedidos_valor_tratado
15                prazo_entrega_pedidos
16               primeiro_ultimo_pedido
17                             products
18             rank_pedidos_por_cliente
19        relatorio_categorias_clientes
20             status_clientes_180_dias
21                status_venda_produtos
22              valor_medio_por_cliente
23              vendas_ultimos_12_meses

In [5]:
dfs = {}
for nome in tabelas['name']:
    dfs[nome] = pd.read_sql(f"SELECT * FROM {nome};", conn)

In [7]:
dfs['clientes_total_gasto_pagos'].head()

               nome  total_gasto
0         Ana Souza         2500
1  Beatriz Oliveira          650
2       Carlos Lima          580
3     Fernanda Lima         2180
4     Gabriel Rocha          710

In [8]:
import sqlite3, pandas as pd
conn = sqlite3.connect('/content/Desafio_SQL_2.db')

tabelas = pd.read_sql(
    "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name;",
    conn
)
dfs = {nome: pd.read_sql(f"SELECT * FROM {nome};", conn)
       for nome in tabelas['name']}

In [9]:
dfs['customers'].head()

   customer_id              nome               email dt_cadastro
0            1      João Pereira      joao@gmail.com  2024-01-10
1            2         Ana Souza       ana@yahoo.com  2024-02-15
2            3       Carlos Lima  carlos@hotmail.com  2024-03-05
3            4  Beatriz Oliveira     bia@outlook.com  2024-04-20
4            5      Pedro Santos     pedro@gmail.com  2024-05-01

In [10]:
dfs['orders'].head()

   order_id  customer_id   dt_pedido  valor_total     status
0       101            1  2024-06-01         3620       Pago
1       102            1  2024-07-10          120       Pago
2       103            2  2024-07-15         2500       Pago
3       104            2  2024-08-20            0  Cancelado
4       105            3  2024-08-25          490       Pago

In [11]:
dfs['products'].head()

   product_id                nome  preco    categoria
0           1     Notebook Lenovo   3500  Eletrônicos
1           2  Smartphone Samsung   2500  Eletrônicos
2           3         Camisa Polo    120       Roupas
3           4          Tênis Nike    400       Roupas
4           5  Livro SQL Avançado     90       Livros

In [12]:
dfs['order_items'].head()

   order_item_id  order_id  product_id  quantidade  preco_unitario
0           1001       101           1           1            3500
1           1002       101           5           1             120
2           1003       102           3           1             120
3           1004       103           2           1            2500
4           1005       104           8           1             180

In [13]:
dfs['media_movel_3_pedidos'].head()

   ID_Cliente  ID_Pedido  Valor_Pedido  Media_Movel_3
0           1        101          3620         3620.0
1           1        102           120         1870.0
2           2        103          2500         2500.0
3           2        104             0         1250.0
4           3        105           490          490.0

In [14]:
dfs['valor_medio_por_cliente'].head()

   customer_id              nome  valor_medio_gasto
0            1      João Pereira             1870.0
1            2         Ana Souza             1250.0
2            3       Carlos Lima              290.0
3            4  Beatriz Oliveira              325.0
4            5      Pedro Santos             3500.0

In [15]:
dfs['vendas_ultimos_12_meses'].head()

   ano_mes  total_vendas
0  2025-01             0
1  2025-02             0
2  2025-03             0
3  2025-04             0
4  2025-05             0

In [16]:
dfs['status_clientes_180_dias'].head()

               nome   Status
0      João Pereira  Inativo
1         Ana Souza  Inativo
2       Carlos Lima  Inativo
3  Beatriz Oliveira  Inativo
4      Pedro Santos  Inativo

In [17]:
dfs['categoria_valor_pedidos'].head()

   order_id  customer_id categoria
0       101            1      Alto
1       102            1     Médio
2       103            2      Alto
3       105            3     Médio
4       106            3     Baixo

In [18]:
dfs['rank_pedidos_por_cliente'].head()

            cliente  order_id  valor_total  posicao_rank
0         Ana Souza       103         2500             1
1  Beatriz Oliveira       108          400             1
2  Beatriz Oliveira       107          250             2
3       Carlos Lima       105          490             1
4       Carlos Lima       106           90             2

In [19]:
dfs['customers'].head()                     # tabela customers
dfs['orders'].head()                        # tabela orders
dfs['products'].head()                      # tabela products
dfs['order_items'].head()                   # tabela order_items
dfs['media_movel_3_pedidos'].head()        # etc.
dfs['valor_medio_por_cliente'].head()
dfs['vendas_ultimos_12_meses'].head()
dfs['status_clientes_180_dias'].head()
dfs['categoria_valor_pedidos'].head()
dfs['rank_pedidos_por_cliente'].head()

            cliente  order_id  valor_total  posicao_rank
0         Ana Souza       103         2500             1
1  Beatriz Oliveira       108          400             1
2  Beatriz Oliveira       107          250             2
3       Carlos Lima       105          490             1
4       Carlos Lima       106           90             2

In [20]:
import pandas as pd

# listar views
views = pd.read_sql(
    "SELECT name FROM sqlite_master WHERE type='view' ORDER BY name;",
    conn
)
views

                 name
0  faturamento_diario

In [21]:
faturamento_diario = pd.read_sql("SELECT * FROM faturamento_diario;", conn)
faturamento_diario.head()

          dia  faturamento_total  qtd_pedidos
0  2024-06-01               3620            1
1  2024-06-20                750            1
2  2024-07-10                120            1
3  2024-07-15               2500            1
4  2024-07-22                900            1