<a href="https://colab.research.google.com/github/ingridcos/Exercicios-WoMakersCode/blob/main/Projeto_Pipeline_de_ETL_Integrado_Ingrid_Semana_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import pandas as pd

EXTRAÇÃO

In [13]:
# carregando o arquivo CSV
df = pd.read_csv("estilo_de_vida.csv")

In [14]:
# Lendo as primeiras 5 linhas do df
df.head()

,Age,Gender,Weight (kg),Height (m),Max_BPM,Avg_BPM,Resting_BPM,Session_Duration (hours),Calories_Burned,Workout_Type,...,cal_from_macros,pct_carbs,protein_per_kg,pct_HRR,pct_maxHR,cal_balance,lean_mass_kg,expected_burn,Burns Calories (per 30 min)_bc,Burns_Calories_Bin
0,34.91,Male,65.27,1.62,188.58,157.65,69.05,1.00,1080.90,Strength,...,2139.59,0.500432,1.624789,0.741237,0.835985,725.10,47.777394,685.1600,7.260425e+19,Medium
1,23.37,Female,56.41,1.55,179.43,131.75,73.18,1.37,1809.91,HIIT,...,1711.65,0.500850,1.514093,0.551247,0.734270,-232.91,40.809803,978.6184,1.020506e+20,High
2,33.20,Female,58.98,1.67,175.04,123.95,54.96,0.91,802.26,Cardio,...,1965.92,0.500610,1.663445,0.574534,0.708124,805.74,44.635580,654.5266,1.079607e+20,High
3,38.69,Female,93.78,1.70,191.21,155.10,50.07,1.10,1450.79,HIIT,...,1627.28,0.499533,0.862017,0.744155,0.811150,1206.21,63.007432,773.6300,8.987921e+19,High
4,45.09,Male,52.42,1.88,193.58,152.88,70.84,1.08,1166.40,Strength,...,2659.23,0.500581,2.538153,0.668405,0.789751,303.60,43.347504,711.4176,5.264685e+19,Low

In [15]:
# Mostrar todas as colunas (lista nomes)
df.columns

Index(['Age', 'Gender', 'Weight (kg)', 'Height (m)', 'Max_BPM', 'Avg_BPM',
       'Resting_BPM', 'Session_Duration (hours)', 'Calories_Burned',
       'Workout_Type', 'Fat_Percentage', 'Water_Intake (liters)',
       'Workout_Frequency (days/week)', 'Experience_Level', 'BMI',
       'Daily meals frequency', 'Physical exercise', 'Carbs', 'Proteins',
       'Fats', 'Calories', 'meal_name', 'meal_type', 'diet_type', 'sugar_g',
       'sodium_mg', 'cholesterol_mg', 'serving_size_g', 'cooking_method',
       'prep_time_min', 'cook_time_min', 'rating', 'Name of Exercise', 'Sets',
       'Reps', 'Benefit', 'Burns Calories (per 30 min)', 'Target Muscle Group',
       'Equipment Needed', 'Difficulty Level', 'Body Part', 'Type of Muscle',
       'Workout', 'BMI_calc', 'cal_from_macros', 'pct_carbs', 'protein_per_kg',
       'pct_HRR', 'pct_maxHR', 'cal_balance', 'lean_mass_kg', 'expected_burn',
       'Burns Calories (per 30 min)_bc', 'Burns_Calories_Bin'],
      dtype='object')

In [16]:
# salvar em csv - bronze
df.to_csv('estilo_de_vida_bronze.csv', index=False)

print('Arquivo salvo com sucesso!')

Arquivo salvo com sucesso!

TRANSFORMAÇÃO

In [17]:
# faz a leitura do arquivo csv bronze
df_bronze = pd.read_csv('estilo_de_vida_bronze.csv')

df_bronze.head()

,Age,Gender,Weight (kg),Height (m),Max_BPM,Avg_BPM,Resting_BPM,Session_Duration (hours),Calories_Burned,Workout_Type,...,cal_from_macros,pct_carbs,protein_per_kg,pct_HRR,pct_maxHR,cal_balance,lean_mass_kg,expected_burn,Burns Calories (per 30 min)_bc,Burns_Calories_Bin
0,34.91,Male,65.27,1.62,188.58,157.65,69.05,1.00,1080.90,Strength,...,2139.59,0.500432,1.624789,0.741237,0.835985,725.10,47.777394,685.1600,7.260425e+19,Medium
1,23.37,Female,56.41,1.55,179.43,131.75,73.18,1.37,1809.91,HIIT,...,1711.65,0.500850,1.514093,0.551247,0.734270,-232.91,40.809803,978.6184,1.020506e+20,High
2,33.20,Female,58.98,1.67,175.04,123.95,54.96,0.91,802.26,Cardio,...,1965.92,0.500610,1.663445,0.574534,0.708124,805.74,44.635580,654.5266,1.079607e+20,High
3,38.69,Female,93.78,1.70,191.21,155.10,50.07,1.10,1450.79,HIIT,...,1627.28,0.499533,0.862017,0.744155,0.811150,1206.21,63.007432,773.6300,8.987921e+19,High
4,45.09,Male,52.42,1.88,193.58,152.88,70.84,1.08,1166.40,Strength,...,2659.23,0.500581,2.538153,0.668405,0.789751,303.60,43.347504,711.4176,5.264685e+19,Low

In [18]:
# Escolhendo as colunas a serem trabalhadas
df_bronze = df_bronze[['Gender', 'Age', 'Weight (kg)', 'Fat_Percentage', 'BMI', 'diet_type', 'Workout_Type', 'Workout_Frequency (days/week)', 'Experience_Level']]

df_bronze.head()

,Gender,Age,Weight (kg),Fat_Percentage,BMI,diet_type,Workout_Type,Workout_Frequency (days/week),Experience_Level
0,Male,34.91,65.27,26.800377,24.87,Vegan,Strength,3.99,2.01
1,Female,23.37,56.41,27.655021,23.48,Vegetarian,HIIT,4.00,2.01
2,Female,33.20,58.98,24.320821,21.15,Paleo,Cardio,2.99,1.02
3,Female,38.69,93.78,32.813572,32.45,Paleo,HIIT,3.99,1.99
4,Male,45.09,52.42,17.307319,14.83,Vegan,Strength,4.00,2.00

In [19]:
# Renomeando as colunas
df_bronze = df_bronze.rename(columns={
  "Gender" : "genero",
  "Age" : "idade",
  "Weight (kg)" : "peso",
  "Fat_Percentage" : "percentual_de_gordura",
  "BMI" : "imc",
  "diet_type" : "tipo_de_dieta",
  "Workout_Type" : "tipo_de_treino",
  "Workout_Frequency (days/week)" : "frequencia_de_treino_semanal",
  "Experience_Level" : "nivel_de_experiencia"
})

df_bronze.head()

,genero,idade,peso,percentual_de_gordura,imc,tipo_de_dieta,tipo_de_treino,frequencia_de_treino_semanal,nivel_de_experiencia
0,Male,34.91,65.27,26.800377,24.87,Vegan,Strength,3.99,2.01
1,Female,23.37,56.41,27.655021,23.48,Vegetarian,HIIT,4.00,2.01
2,Female,33.20,58.98,24.320821,21.15,Paleo,Cardio,2.99,1.02
3,Female,38.69,93.78,32.813572,32.45,Paleo,HIIT,3.99,1.99
4,Male,45.09,52.42,17.307319,14.83,Vegan,Strength,4.00,2.00

In [20]:
# Cria lista do genero
df_bronze["genero"].unique().tolist()

['Male', 'Female']

In [21]:
# Cria lista do tipo de dieta
df_bronze["tipo_de_dieta"].unique().tolist()

['Vegan', 'Vegetarian', 'Paleo', 'Keto', 'Low-Carb', 'Balanced']

In [22]:
# Cria lista do tipo de treino
df_bronze["tipo_de_treino"].unique().tolist()

['Strength', 'HIIT', 'Cardio', 'Yoga']

In [23]:
# Traduzindo termos Gênero
df_bronze["genero"] = df_bronze["genero"].map({
    "Male": "Masculino",
    "Female": "Feminino"
})

In [24]:
# Traduzindo termos Tipo de Dieta
df_bronze["tipo_de_dieta"] = df_bronze["tipo_de_dieta"].map({
    "Vegan": "Vegana",
    "Vegetarian": "Vegetariana",
    "Paleo": "Paleolítica",
    "Keto": "Cetogênica",
    "Low-Carb": "Baixo Carboidrato",
    "Balanced": "Balanceada"
})

In [25]:
# Traduzindo Tipo de Treino
df_bronze["tipo_de_treino"] = df_bronze["tipo_de_treino"].map({
    "Strength": "Força",
    "HIIT": "HIIT",
    "Cardio": "Cardio",
    "Yoga": "Yoga"
})

In [26]:
df_bronze.head()

,genero,idade,peso,percentual_de_gordura,imc,tipo_de_dieta,tipo_de_treino,frequencia_de_treino_semanal,nivel_de_experiencia
0,Masculino,34.91,65.27,26.800377,24.87,Vegana,Força,3.99,2.01
1,Feminino,23.37,56.41,27.655021,23.48,Vegetariana,HIIT,4.00,2.01
2,Feminino,33.20,58.98,24.320821,21.15,Paleolítica,Cardio,2.99,1.02
3,Feminino,38.69,93.78,32.813572,32.45,Paleolítica,HIIT,3.99,1.99
4,Masculino,45.09,52.42,17.307319,14.83,Vegana,Força,4.00,2.00

In [27]:
# Arredondamento para 1 Casa Decimal
df_bronze["percentual_de_gordura"] = df_bronze["percentual_de_gordura"].round(1)
df_bronze["peso"] = df_bronze["peso"].round(1)
df_bronze["imc"] = df_bronze["imc"].round(1)

In [28]:
df_bronze.head(13)

,genero,idade,peso,percentual_de_gordura,imc,tipo_de_dieta,tipo_de_treino,frequencia_de_treino_semanal,nivel_de_experiencia
0,Masculino,34.91,65.3,26.8,24.9,Vegana,Força,3.99,2.01
1,Feminino,23.37,56.4,27.7,23.5,Vegetariana,HIIT,4.00,2.01
2,Feminino,33.20,59.0,24.3,21.2,Paleolítica,Cardio,2.99,1.02
3,Feminino,38.69,93.8,32.8,32.4,Paleolítica,HIIT,3.99,1.99
4,Masculino,45.09,52.4,17.3,14.8,Vegana,Força,4.00,2.00
5,Feminino,53.19,105.0,32.0,31.0,Cetogênica,Yoga,3.02,1.00
6,Masculino,23.17,58.4,20.5,18.4,Baixo Carboidrato,Força,4.96,3.00
7,Feminino,55.92,84.1,32.1,31.6,Baixo Carboidrato,Yoga,3.97,2.01
8,Feminino,24.11,88.6,27.4,27.6,Vegana,Força,4.01,3.02
9,Feminino,39.19,50.3,21.9,19.7,Paleolítica,Força,2.00,1.00
10,Masculino,50.51,86.4,29.1,32.5,Cetogênica,Força,4.01,2.98
11,Feminino,47.77,83.9,23.6,25.3,Cetogênica,HIIT,5.02,3.01
12,Masculino,19.00,82.7,24.1,21.5,Vegana,HIIT,5.02,2.99

In [29]:
# Transformando várias colunas para int
df_bronze['frequencia_de_treino_semanal'] = df_bronze['frequencia_de_treino_semanal'].astype(int)
df_bronze.head()

,genero,idade,peso,percentual_de_gordura,imc,tipo_de_dieta,tipo_de_treino,frequencia_de_treino_semanal,nivel_de_experiencia
0,Masculino,34.91,65.3,26.8,24.9,Vegana,Força,3,2.01
1,Feminino,23.37,56.4,27.7,23.5,Vegetariana,HIIT,4,2.01
2,Feminino,33.20,59.0,24.3,21.2,Paleolítica,Cardio,2,1.02
3,Feminino,38.69,93.8,32.8,32.4,Paleolítica,HIIT,3,1.99
4,Masculino,45.09,52.4,17.3,14.8,Vegana,Força,4,2.00

In [30]:
df_bronze['idade'] = df_bronze['idade'].astype(int)
df_bronze.head()

,genero,idade,peso,percentual_de_gordura,imc,tipo_de_dieta,tipo_de_treino,frequencia_de_treino_semanal,nivel_de_experiencia
0,Masculino,34,65.3,26.8,24.9,Vegana,Força,3,2.01
1,Feminino,23,56.4,27.7,23.5,Vegetariana,HIIT,4,2.01
2,Feminino,33,59.0,24.3,21.2,Paleolítica,Cardio,2,1.02
3,Feminino,38,93.8,32.8,32.4,Paleolítica,HIIT,3,1.99
4,Masculino,45,52.4,17.3,14.8,Vegana,Força,4,2.00

In [31]:
df_bronze['nivel_de_experiencia'] = df_bronze['nivel_de_experiencia'].astype(int)
df_bronze.head()

,genero,idade,peso,percentual_de_gordura,imc,tipo_de_dieta,tipo_de_treino,frequencia_de_treino_semanal,nivel_de_experiencia
0,Masculino,34,65.3,26.8,24.9,Vegana,Força,3,2
1,Feminino,23,56.4,27.7,23.5,Vegetariana,HIIT,4,2
2,Feminino,33,59.0,24.3,21.2,Paleolítica,Cardio,2,1
3,Feminino,38,93.8,32.8,32.4,Paleolítica,HIIT,3,1
4,Masculino,45,52.4,17.3,14.8,Vegana,Força,4,2

In [32]:
# Substituição dos Códigos de Experiência por Categorias
df_bronze["nivel_de_experiencia"] = df_bronze["nivel_de_experiencia"].map({
    1: "Iniciante",
    2: "Intermediário",
    3: "Avançado"
})
df_bronze.head()

,genero,idade,peso,percentual_de_gordura,imc,tipo_de_dieta,tipo_de_treino,frequencia_de_treino_semanal,nivel_de_experiencia
0,Masculino,34,65.3,26.8,24.9,Vegana,Força,3,Intermediário
1,Feminino,23,56.4,27.7,23.5,Vegetariana,HIIT,4,Intermediário
2,Feminino,33,59.0,24.3,21.2,Paleolítica,Cardio,2,Iniciante
3,Feminino,38,93.8,32.8,32.4,Paleolítica,HIIT,3,Iniciante
4,Masculino,45,52.4,17.3,14.8,Vegana,Força,4,Intermediário

In [33]:
# salvar em csv - prata
df_bronze.to_csv('estilo_de_vida_silver.csv', index=False)

print('Arquivo salvo com sucesso!')

Arquivo salvo com sucesso!

In [34]:
# faz a leitura do arquivo csv silver
df_gold = pd.read_csv('estilo_de_vida_silver.csv')

df_gold.head()

,genero,idade,peso,percentual_de_gordura,imc,tipo_de_dieta,tipo_de_treino,frequencia_de_treino_semanal,nivel_de_experiencia
0,Masculino,34,65.3,26.8,24.9,Vegana,Força,3,Intermediário
1,Feminino,23,56.4,27.7,23.5,Vegetariana,HIIT,4,Intermediário
2,Feminino,33,59.0,24.3,21.2,Paleolítica,Cardio,2,Iniciante
3,Feminino,38,93.8,32.8,32.4,Paleolítica,HIIT,3,Iniciante
4,Masculino,45,52.4,17.3,14.8,Vegana,Força,4,Intermediário

In [35]:
# Função de Classificação do Índice de Massa Corporal
def classificar_imc(imc):
    if imc < 18.5:
        return "Abaixo do Peso"
    elif 18.5 <= imc <= 24.9:
        return "Peso Normal"
    elif 25.0 <= imc <= 29.9:
        return "Sobrepeso"
    elif 30.0 <= imc <= 34.9:
        return "Obesidade Grau I"
    elif 35.0 <= imc <= 39.9:
        return "Obesidade Grau II"
    else:
        return "Obesidade Grau III"

df_gold["classificacao_imc"] = df_gold["imc"].apply(classificar_imc)

df_gold.head()

,genero,idade,peso,percentual_de_gordura,imc,tipo_de_dieta,tipo_de_treino,frequencia_de_treino_semanal,nivel_de_experiencia,classificacao_imc
0,Masculino,34,65.3,26.8,24.9,Vegana,Força,3,Intermediário,Peso Normal
1,Feminino,23,56.4,27.7,23.5,Vegetariana,HIIT,4,Intermediário,Peso Normal
2,Feminino,33,59.0,24.3,21.2,Paleolítica,Cardio,2,Iniciante,Peso Normal
3,Feminino,38,93.8,32.8,32.4,Paleolítica,HIIT,3,Iniciante,Obesidade Grau I
4,Masculino,45,52.4,17.3,14.8,Vegana,Força,4,Intermediário,Abaixo do Peso

In [36]:
# mover para a 6ª posição (índice 5)
colunas = list(df_gold.columns)
colunas.insert(5, colunas.pop(colunas.index("classificacao_imc")))

df_gold = df_gold[colunas]

df_gold.head()

,genero,idade,peso,percentual_de_gordura,imc,classificacao_imc,tipo_de_dieta,tipo_de_treino,frequencia_de_treino_semanal,nivel_de_experiencia
0,Masculino,34,65.3,26.8,24.9,Peso Normal,Vegana,Força,3,Intermediário
1,Feminino,23,56.4,27.7,23.5,Peso Normal,Vegetariana,HIIT,4,Intermediário
2,Feminino,33,59.0,24.3,21.2,Peso Normal,Paleolítica,Cardio,2,Iniciante
3,Feminino,38,93.8,32.8,32.4,Obesidade Grau I,Paleolítica,HIIT,3,Iniciante
4,Masculino,45,52.4,17.3,14.8,Abaixo do Peso,Vegana,Força,4,Intermediário

In [37]:
# mover para a 6ª posição (índice 5)
colunas = list(df_gold.columns)
colunas.insert(5, colunas.pop(colunas.index("classificacao_imc")))

df_gold = df_gold[colunas]

df_gold.head()

,genero,idade,peso,percentual_de_gordura,imc,classificacao_imc,tipo_de_dieta,tipo_de_treino,frequencia_de_treino_semanal,nivel_de_experiencia
0,Masculino,34,65.3,26.8,24.9,Peso Normal,Vegana,Força,3,Intermediário
1,Feminino,23,56.4,27.7,23.5,Peso Normal,Vegetariana,HIIT,4,Intermediário
2,Feminino,33,59.0,24.3,21.2,Peso Normal,Paleolítica,Cardio,2,Iniciante
3,Feminino,38,93.8,32.8,32.4,Obesidade Grau I,Paleolítica,HIIT,3,Iniciante
4,Masculino,45,52.4,17.3,14.8,Abaixo do Peso,Vegana,Força,4,Intermediário

CARREGAMENTO

In [38]:
from sqlalchemy import create_engine

In [39]:
# cria o banco
engine = create_engine('sqlite:///estilo_de_vida_final.db')

# salva todas as tabelas no banco criado
df.to_sql('estilo_de_vida_bronze', con=engine, if_exists='replace', index=False)
df_bronze.to_sql('estilo_de_vida_silver', con=engine, if_exists='replace', index=False)
df_gold.to_sql('estilo_de_vida_gold', con=engine, if_exists='replace', index=False)

20000