<a href="https://colab.research.google.com/github/ingridcos/Exercicios-WoMakersCode/blob/main/Desafio_SQL1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import pandas as pd

In [2]:
alunos = pd.read_csv("/content/ALUNOS.csv")
cursos = pd.read_csv("/content/CURSOS.csv")
matriculas = pd.read_csv("/content/MATRICULAS.csv")

In [3]:
print("ALUNOS:")
display(alunos)
print("CURSOS:")
display(cursos)
print("MATRICULAS:")
display(matriculas)

ALUNOS:

   ID_ALUNO     NOME_ALUNO                EMAIL DATA_INGRESSO
0         1  Lucas Martins    lucas.m@email.com    2023-02-01
1         2  Sofia Pereira    sofia.p@email.com    2023-02-01
2         3  Mariana Costa  mariana.c@email.com    2022-08-01
3         4  Rafael Santos   rafael.s@email.com    2024-02-01

CURSOS:

   ID_CURSO                 NOME_CURSO           DEPARTAMENTO  CREDITOS
0       101   Algoritmos e Programação  Ciência da Computação         4
1       102                  Cálculo I             Matemática         6
2       103  Administração de Empresas                 Gestão         4
3       104         Estrutura de Dados  Ciência da Computação         6

MATRICULAS:

   ID_MATRICULA  ID_ALUNO  ID_CURSO  NOTA_FINAL
0             1         1       101         8.5
1             2         1       102         7.0
2             3         2       101         9.0
3             4         2       104         8.8
4             5         3       103         6.5

In [4]:
conn = sqlite3.connect("/content/Desafio-SQL1.db")
cursor = conn.cursor()

In [6]:
# Criar tabelas
cursor.execute("""
CREATE TABLE IF NOT EXISTS ALUNOS (
    ID_ALUNO INT PRIMARY KEY,
    NOME_ALUNO VARCHAR(150),
    EMAIL VARCHAR(100),
    DATA_INGRESSO DATE
);
""")

cursor.execute("""
CREATE TABLE IF NOT EXISTS CURSOS (
    ID_CURSO INT PRIMARY KEY,
    NOME_CURSO VARCHAR(100),
    DEPARTAMENTO VARCHAR(100),
    CREDITOS INT
);
""")

cursor.execute("""
CREATE TABLE IF NOT EXISTS MATRICULAS (
    ID_MATRICULA INT PRIMARY KEY,
    ID_ALUNO INT,
    ID_CURSO INT,
    NOTA_FINAL DECIMAL(4,2),
    FOREIGN KEY (ID_ALUNO) REFERENCES ALUNOS(ID_ALUNO),
    FOREIGN KEY (ID_CURSO) REFERENCES CURSOS(ID_CURSO)
);
""")

In [7]:
#Inserir os dados dos CSVs nas tabelas
alunos.to_sql('ALUNOS', conn, if_exists='replace', index=False)
cursos.to_sql('CURSOS', conn, if_exists='replace', index=False)
matriculas.to_sql('MATRICULAS', conn, if_exists='replace', index=False)

conn.commit()

print("Tabelas criadas e dados importados com sucesso!")

Tabelas criadas e dados importados com sucesso!

In [8]:
query = """
SELECT * FROM ALUNOS;
"""
pd.read_sql_query(query, conn)

   ID_ALUNO     NOME_ALUNO                EMAIL DATA_INGRESSO
0         1  Lucas Martins    lucas.m@email.com    2023-02-01
1         2  Sofia Pereira    sofia.p@email.com    2023-02-01
2         3  Mariana Costa  mariana.c@email.com    2022-08-01
3         4  Rafael Santos   rafael.s@email.com    2024-02-01

In [9]:
query = """
SELECT
    A.NOME_ALUNO,
    ROUND(AVG(M.NOTA_FINAL), 2) AS MEDIA
FROM ALUNOS A
JOIN MATRICULAS M ON A.ID_ALUNO = M.ID_ALUNO
GROUP BY A.NOME_ALUNO
ORDER BY MEDIA DESC
LIMIT 1;
"""
pd.read_sql_query(query, conn)

      NOME_ALUNO  MEDIA
0  Sofia Pereira    8.9

In [10]:
# Mostrar as tabelas
print("Tabelas no banco:")
tables = cursor.execute("SELECT name FROM sqlite_master WHERE type='table';").fetchall()
for t in tables:
    print("-", t[0])

Tabelas no banco:
- ALUNOS
- CURSOS
- MATRICULAS

In [11]:
for t in tables:
    print(f"\n============ {t[0]} ============")
    df = pd.read_sql_query(f"SELECT * FROM {t[0]};", conn)
    display(df)

============ ALUNOS ============

   ID_ALUNO     NOME_ALUNO                EMAIL DATA_INGRESSO
0         1  Lucas Martins    lucas.m@email.com    2023-02-01
1         2  Sofia Pereira    sofia.p@email.com    2023-02-01
2         3  Mariana Costa  mariana.c@email.com    2022-08-01
3         4  Rafael Santos   rafael.s@email.com    2024-02-01

============ CURSOS ============

   ID_CURSO                 NOME_CURSO           DEPARTAMENTO  CREDITOS
0       101   Algoritmos e Programação  Ciência da Computação         4
1       102                  Cálculo I             Matemática         6
2       103  Administração de Empresas                 Gestão         4
3       104         Estrutura de Dados  Ciência da Computação         6

============ MATRICULAS ============

   ID_MATRICULA  ID_ALUNO  ID_CURSO  NOTA_FINAL
0             1         1       101         8.5
1             2         1       102         7.0
2             3         2       101         9.0
3             4         2       104         8.8
4             5         3       103         6.5